export const events = [
  {
    title: "KubeCon + CloudNativeCon North America 2026",
    image: "/images/event1.png",
    slug: "kubecon-cloudnativecon-north-america-2026",
    location: "Atlanta, GA, USA",
    date: "November 17–20, 2026",
    time: "8:30 AM–6:00 PM (daily)",
  },
  {
    title: "AWS re:Invent 2026",
    image: "/images/event2.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV, USA",
    date: "December 1–5, 2026",
    time: "Keynotes morning; expo & sessions all day",
  },
  {
    title: "PyCon US 2026",
    image: "/images/event3.png",
    slug: "pycon-us-2026",
    location: "Pittsburgh, PA, USA",
    date: "May 14–22, 2026",
    time: "Tutorials May 14–15; talks May 16–17",
  },
  {
    title: "HackMIT 2026",
    image: "/images/event4.png",
    slug: "hackmit-2026",
    location: "Cambridge, MA, USA",
    date: "September 19–21, 2026",
    time: "48-hour hackathon; check-in Fri evening",
  },
  {
    title: "Devoxx Belgium 2026",
    image: "/images/event5.png",
    slug: "devoxx-belgium-2026",
    location: "Antwerp, Belgium",
    date: "October 5–9, 2026",
    time: "9:00 AM–6:30 PM (conference days)",
  },
  {
    title: "Paris TypeScript Meetup × React Paris",
    image: "/images/event6.png",
    slug: "paris-typescript-meetup-react-paris-june-2026",
    location: "Paris, France",
    date: "June 18, 2026",
    time: "6:30 PM–9:30 PM CET",
  },
];
